# Generated by Django 3.1.6 on 2021-02-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(verbose_name='Priority')),
                ('name', models.CharField(max_length=150, verbose_name='Category name')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('priority',),
            },
        ),
    ]
