# Generated by Django 3.1.6 on 2021-02-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Is active')),
                ('priority', models.PositiveIntegerField(verbose_name='Priority')),
                ('name', models.CharField(max_length=150, verbose_name='Item')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ('priority',),
            },
        ),
    ]
