# Generated by Django 3.1.6 on 2021-03-02 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210227_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Is active')),
                ('priority', models.PositiveIntegerField(verbose_name='Priority')),
                ('name', models.CharField(max_length=150, verbose_name='Characteristic')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalog.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Characteristic',
                'verbose_name_plural': 'Characteristics',
                'ordering': ('priority',),
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CharacteristicValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Is active')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.characteristic', verbose_name='Characteristic')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Characteristic value',
                'verbose_name_plural': 'Characteristic values',
                'ordering': ('characteristic__priority',),
                'unique_together': {('characteristic', 'item')},
            },
        ),
    ]
