# Generated by Django 3.1.6 on 2021-03-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210302_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalog.category', verbose_name='Category'),
        ),
    ]
