# Generated by Django 3.1.6 on 2021-03-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210302_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='preview',
            field=models.ImageField(blank=True, upload_to='category_preview/', verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='characteristicvalue',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Selected'),
        ),
    ]
